/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EstateRouteImport } from './routes/estate'
import { Route as EstateIndexRouteImport } from './routes/estate.index'
import { Route as EstateChronicleRouteImport } from './routes/estate.chronicle'
import { Route as EstateDockRouteImport } from './routes/estate.dock'
import { Route as EstateHallRouteImport } from './routes/estate.hall'
import { Route as EstateHouseholdRouteImport } from './routes/estate.household'
import { Route as EstateHutRouteImport } from './routes/estate.hut'
import { Route as EstateWallRouteImport } from './routes/estate.wall'
import { Route as EstateYardRouteImport } from './routes/estate.yard'
import { Route as EstateExploreRouteIdRouteImport } from './routes/estate.explore.$routeId'
import { Route as EstateHouseholdIndexRouteImport } from './routes/estate.household.index'
import { Route as EstateHouseholdPersonIdRouteImport } from './routes/estate.household.$personId'
import { Route as EstateLotLotIdRouteImport } from './routes/estate.lot.$lotId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EstateRoute = EstateRouteImport.update({
  id: '/estate',
  path: '/estate',
  getParentRoute: () => rootRouteImport,
} as any)
const EstateIndexRoute = EstateIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstateRoute,
} as any)
const EstateChronicleRoute = EstateChronicleRouteImport.update({
  id: '/chronicle',
  path: '/chronicle',
  getParentRoute: () => EstateRoute,
} as any)
const EstateDockRoute = EstateDockRouteImport.update({
  id: '/dock',
  path: '/dock',
  getParentRoute: () => EstateRoute,
} as any)
const EstateHallRoute = EstateHallRouteImport.update({
  id: '/hall',
  path: '/hall',
  getParentRoute: () => EstateRoute,
} as any)
const EstateHouseholdRoute = EstateHouseholdRouteImport.update({
  id: '/household',
  path: '/household',
  getParentRoute: () => EstateRoute,
} as any)
const EstateHutRoute = EstateHutRouteImport.update({
  id: '/hut',
  path: '/hut',
  getParentRoute: () => EstateRoute,
} as any)
const EstateWallRoute = EstateWallRouteImport.update({
  id: '/wall',
  path: '/wall',
  getParentRoute: () => EstateRoute,
} as any)
const EstateYardRoute = EstateYardRouteImport.update({
  id: '/yard',
  path: '/yard',
  getParentRoute: () => EstateRoute,
} as any)
const EstateExploreRouteIdRoute = EstateExploreRouteIdRouteImport.update({
  id: '/explore/$routeId',
  path: '/explore/$routeId',
  getParentRoute: () => EstateRoute,
} as any)
const EstateHouseholdIndexRoute = EstateHouseholdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EstateHouseholdRoute,
} as any)
const EstateHouseholdPersonIdRoute = EstateHouseholdPersonIdRouteImport.update({
  id: '/$personId',
  path: '/$personId',
  getParentRoute: () => EstateHouseholdRoute,
} as any)
const EstateLotLotIdRoute = EstateLotLotIdRouteImport.update({
  id: '/lot/$lotId',
  path: '/lot/$lotId',
  getParentRoute: () => EstateRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/estate': typeof EstateRouteWithChildren
  '/estate/chronicle': typeof EstateChronicleRoute
  '/estate/dock': typeof EstateDockRoute
  '/estate/hall': typeof EstateHallRoute
  '/estate/household': typeof EstateHouseholdRouteWithChildren
  '/estate/hut': typeof EstateHutRoute
  '/estate/wall': typeof EstateWallRoute
  '/estate/yard': typeof EstateYardRoute
  '/estate/': typeof EstateIndexRoute
  '/estate/explore/$routeId': typeof EstateExploreRouteIdRoute
  '/estate/household/$personId': typeof EstateHouseholdPersonIdRoute
  '/estate/lot/$lotId': typeof EstateLotLotIdRoute
  '/estate/household/': typeof EstateHouseholdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/estate/chronicle': typeof EstateChronicleRoute
  '/estate/dock': typeof EstateDockRoute
  '/estate/hall': typeof EstateHallRoute
  '/estate/hut': typeof EstateHutRoute
  '/estate/wall': typeof EstateWallRoute
  '/estate/yard': typeof EstateYardRoute
  '/estate': typeof EstateIndexRoute
  '/estate/explore/$routeId': typeof EstateExploreRouteIdRoute
  '/estate/household/$personId': typeof EstateHouseholdPersonIdRoute
  '/estate/lot/$lotId': typeof EstateLotLotIdRoute
  '/estate/household': typeof EstateHouseholdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/estate': typeof EstateRouteWithChildren
  '/estate/chronicle': typeof EstateChronicleRoute
  '/estate/dock': typeof EstateDockRoute
  '/estate/hall': typeof EstateHallRoute
  '/estate/household': typeof EstateHouseholdRouteWithChildren
  '/estate/hut': typeof EstateHutRoute
  '/estate/wall': typeof EstateWallRoute
  '/estate/yard': typeof EstateYardRoute
  '/estate/': typeof EstateIndexRoute
  '/estate/explore/$routeId': typeof EstateExploreRouteIdRoute
  '/estate/household/$personId': typeof EstateHouseholdPersonIdRoute
  '/estate/lot/$lotId': typeof EstateLotLotIdRoute
  '/estate/household/': typeof EstateHouseholdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/estate'
    | '/estate/chronicle'
    | '/estate/dock'
    | '/estate/hall'
    | '/estate/household'
    | '/estate/hut'
    | '/estate/wall'
    | '/estate/yard'
    | '/estate/'
    | '/estate/explore/$routeId'
    | '/estate/household/$personId'
    | '/estate/lot/$lotId'
    | '/estate/household/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/estate/chronicle'
    | '/estate/dock'
    | '/estate/hall'
    | '/estate/hut'
    | '/estate/wall'
    | '/estate/yard'
    | '/estate'
    | '/estate/explore/$routeId'
    | '/estate/household/$personId'
    | '/estate/lot/$lotId'
    | '/estate/household'
  id:
    | '__root__'
    | '/'
    | '/estate'
    | '/estate/chronicle'
    | '/estate/dock'
    | '/estate/hall'
    | '/estate/household'
    | '/estate/hut'
    | '/estate/wall'
    | '/estate/yard'
    | '/estate/'
    | '/estate/explore/$routeId'
    | '/estate/household/$personId'
    | '/estate/lot/$lotId'
    | '/estate/household/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EstateRoute: typeof EstateRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estate': {
      id: '/estate'
      path: '/estate'
      fullPath: '/estate'
      preLoaderRoute: typeof EstateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estate/': {
      id: '/estate/'
      path: '/'
      fullPath: '/estate/'
      preLoaderRoute: typeof EstateIndexRouteImport
      parentRoute: typeof EstateRoute
    }
    '/estate/chronicle': {
      id: '/estate/chronicle'
      path: '/chronicle'
      fullPath: '/estate/chronicle'
      preLoaderRoute: typeof EstateChronicleRouteImport
      parentRoute: typeof EstateRoute
    }
    '/estate/dock': {
      id: '/estate/dock'
      path: '/dock'
      fullPath: '/estate/dock'
      preLoaderRoute: typeof EstateDockRouteImport
      parentRoute: typeof EstateRoute
    }
    '/estate/hall': {
      id: '/estate/hall'
      path: '/hall'
      fullPath: '/estate/hall'
      preLoaderRoute: typeof EstateHallRouteImport
      parentRoute: typeof EstateRoute
    }
    '/estate/household': {
      id: '/estate/household'
      path: '/household'
      fullPath: '/estate/household'
      preLoaderRoute: typeof EstateHouseholdRouteImport
      parentRoute: typeof EstateRoute
    }
    '/estate/hut': {
      id: '/estate/hut'
      path: '/hut'
      fullPath: '/estate/hut'
      preLoaderRoute: typeof EstateHutRouteImport
      parentRoute: typeof EstateRoute
    }
    '/estate/wall': {
      id: '/estate/wall'
      path: '/wall'
      fullPath: '/estate/wall'
      preLoaderRoute: typeof EstateWallRouteImport
      parentRoute: typeof EstateRoute
    }
    '/estate/yard': {
      id: '/estate/yard'
      path: '/yard'
      fullPath: '/estate/yard'
      preLoaderRoute: typeof EstateYardRouteImport
      parentRoute: typeof EstateRoute
    }
    '/estate/explore/$routeId': {
      id: '/estate/explore/$routeId'
      path: '/explore/$routeId'
      fullPath: '/estate/explore/$routeId'
      preLoaderRoute: typeof EstateExploreRouteIdRouteImport
      parentRoute: typeof EstateRoute
    }
    '/estate/household/': {
      id: '/estate/household/'
      path: '/'
      fullPath: '/estate/household/'
      preLoaderRoute: typeof EstateHouseholdIndexRouteImport
      parentRoute: typeof EstateHouseholdRoute
    }
    '/estate/household/$personId': {
      id: '/estate/household/$personId'
      path: '/$personId'
      fullPath: '/estate/household/$personId'
      preLoaderRoute: typeof EstateHouseholdPersonIdRouteImport
      parentRoute: typeof EstateHouseholdRoute
    }
    '/estate/lot/$lotId': {
      id: '/estate/lot/$lotId'
      path: '/lot/$lotId'
      fullPath: '/estate/lot/$lotId'
      preLoaderRoute: typeof EstateLotLotIdRouteImport
      parentRoute: typeof EstateRoute
    }
  }
}

interface EstateHouseholdRouteChildren {
  EstateHouseholdPersonIdRoute: typeof EstateHouseholdPersonIdRoute
  EstateHouseholdIndexRoute: typeof EstateHouseholdIndexRoute
}

const EstateHouseholdRouteChildren: EstateHouseholdRouteChildren = {
  EstateHouseholdPersonIdRoute: EstateHouseholdPersonIdRoute,
  EstateHouseholdIndexRoute: EstateHouseholdIndexRoute,
}

const EstateHouseholdRouteWithChildren = EstateHouseholdRoute._addFileChildren(
  EstateHouseholdRouteChildren,
)

interface EstateRouteChildren {
  EstateChronicleRoute: typeof EstateChronicleRoute
  EstateDockRoute: typeof EstateDockRoute
  EstateHallRoute: typeof EstateHallRoute
  EstateHouseholdRoute: typeof EstateHouseholdRouteWithChildren
  EstateHutRoute: typeof EstateHutRoute
  EstateWallRoute: typeof EstateWallRoute
  EstateYardRoute: typeof EstateYardRoute
  EstateIndexRoute: typeof EstateIndexRoute
  EstateExploreRouteIdRoute: typeof EstateExploreRouteIdRoute
  EstateLotLotIdRoute: typeof EstateLotLotIdRoute
}

const EstateRouteChildren: EstateRouteChildren = {
  EstateChronicleRoute: EstateChronicleRoute,
  EstateDockRoute: EstateDockRoute,
  EstateHallRoute: EstateHallRoute,
  EstateHouseholdRoute: EstateHouseholdRouteWithChildren,
  EstateHutRoute: EstateHutRoute,
  EstateWallRoute: EstateWallRoute,
  EstateYardRoute: EstateYardRoute,
  EstateIndexRoute: EstateIndexRoute,
  EstateExploreRouteIdRoute: EstateExploreRouteIdRoute,
  EstateLotLotIdRoute: EstateLotLotIdRoute,
}

const EstateRouteWithChildren =
  EstateRoute._addFileChildren(EstateRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EstateRoute: EstateRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
